# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS := class_filter
TC_TARGETS := class_filter.bpf
BPF_SKEL_TARGETS := $(TC_TARGETS)

EXTRA_DEPS := parsing_helpers.h

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
